export default class Constant {
  /**
   * log tag
   */
  static readonly TAG = '[Codi]';

  static readonly _CONTAINER_ = '__container__';
  /**
   * 宽或者高100%
   */
  static readonly FULL_PARENT = '100%';
  /**
   * 统一间距
   */
  static readonly COMMON_SPACE = 12;
  /**
   * 单元格行高
   */
  static readonly CELL_HEIGHT_NORMAL = 44;
  /**
   * 窗口管理器
   */
  static readonly KEY_WINDOW_STAGE = 'KEY_WINDOW_STAGE'
  /**
   * 上下文
   */
  static readonly KEY_CONTEXT = 'KEY_CONTEXT'



}