export class TestPosId {
  /**
   * 应用ID
   */
  static readonly APP_ID = '1262';
  /**
   * 开屏测试ID
   */
  static readonly POS_ID_SPLASH = '4000000270';
  /**
   * 激励视频测试ID
   */
  static readonly POS_ID_REWARD = '4000000271';
  /**
   * 插屏测试ID
   */
  static readonly POS_ID_INTERSTITIAL = '4000000272'
  /**
   * 原生广告测试ID
   */
  static readonly POS_ID_NATIVE = '4000000273'
  /**
   * 横幅广告测试ID
   */
  static readonly POS_ID_BANNER = '4000000274'
}